// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc75S4LVjBScDeVkqVC7DATIhok0sxsQk',
    appId: '1:860007084287:web:2b15ef9b69cb02e4fe5cca',
    messagingSenderId: '860007084287',
    projectId: 'yummy-app-262e1',
    authDomain: 'yummy-app-262e1.firebaseapp.com',
    storageBucket: 'yummy-app-262e1.appspot.com',
    measurementId: 'G-2FYJHHGRJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7V0-xsvTjPXfbjGsMAssKayqneGNgFp0',
    appId: '1:860007084287:android:bcee76c5cd68987afe5cca',
    messagingSenderId: '860007084287',
    projectId: 'yummy-app-262e1',
    storageBucket: 'yummy-app-262e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ohydZ4xaeb8ObOzlGk7iygSWVQOekI4',
    appId: '1:860007084287:ios:4d4fcfb6d91d4c49fe5cca',
    messagingSenderId: '860007084287',
    projectId: 'yummy-app-262e1',
    storageBucket: 'yummy-app-262e1.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ohydZ4xaeb8ObOzlGk7iygSWVQOekI4',
    appId: '1:860007084287:ios:4d4fcfb6d91d4c49fe5cca',
    messagingSenderId: '860007084287',
    projectId: 'yummy-app-262e1',
    storageBucket: 'yummy-app-262e1.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc75S4LVjBScDeVkqVC7DATIhok0sxsQk',
    appId: '1:860007084287:web:1c2ad57dbb6aa15efe5cca',
    messagingSenderId: '860007084287',
    projectId: 'yummy-app-262e1',
    authDomain: 'yummy-app-262e1.firebaseapp.com',
    storageBucket: 'yummy-app-262e1.appspot.com',
    measurementId: 'G-7DNGRNX9HC',
  );
}
